public class ExceptionHandlingDemo1 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		int a = 20, b = 0;

		try {
			int arr[] = new int[5];
			arr[5] = 100;

			int result = a / b;
			System.out.println(result);
		} catch (Exception e) {

		}

		System.out.println("Regular code: No error");

	}

}
